apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-intro-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-intro
  template:
    metadata:
      labels:
        app: tech-intro
    spec:
      containers:
      - name: web
        image: abhixnvs/tech-intro-page
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Mi"
            cpu: "1m"
          limits:
            memory: "16Mi"
            cpu: "10m"