apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tech-intro-page
  namespace: webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tech-intro-page
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale when CPU usage > 50%